import { Category, Product, Order, User } from "./types";

// ============================================================
// lib/mock-data.ts — FurnSpace Mock Adatok
// ============================================================

// ------------------------------------------------------------
// Kategóriák (6 db)
// ------------------------------------------------------------
export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Kanapék",
    slug: "kanapek",
    description: "Kényelmes, modern és klasszikus kanapék a nappaliba.",
    image_url: "/images/categories/kanapek.webp",
  },
  {
    id: "cat-2",
    name: "Asztalok",
    slug: "asztalok",
    description: "Étkezőasztalok, dohányzóasztalok és íróasztalok széles választéka.",
    image_url: "/images/categories/asztalok.webp",
  },
  {
    id: "cat-3",
    name: "Székek",
    slug: "szekek",
    description: "Kényelmes étkezőszékek, fotelek és bárszékek.",
    image_url: "/images/categories/szekek.webp",
  },
  {
    id: "cat-4",
    name: "Szekrények",
    slug: "szekrenyek",
    description: "Praktikus tárolómegoldások: ruhásszekrények, komódok és vitrinek.",
    image_url: "/images/categories/szekrenyek.webp",
  },
  {
    id: "cat-5",
    name: "Ágyak",
    slug: "agyak",
    description: "Pihentető alvás minőségi ágykeretekkel és matracokkal.",
    image_url: "/images/categories/agyak.webp",
  },
  {
    id: "cat-6",
    name: "Polcok",
    slug: "polcok",
    description: "Dekoratív és funkcionális könyvespolcok, fali polcok.",
    image_url: "/images/categories/polcok.webp",
  },
];

// ------------------------------------------------------------
// Termékek (18 db - 3 kategóriánként)
// ------------------------------------------------------------
export const MOCK_PRODUCTS: Product[] = [
  // --- Kanapék (cat-1) ---
  {
    id: "prod-1",
    name: "Nordic Soft Kanapé",
    slug: "nordic-soft-kanape",
    description: "Modern, skandináv stílusú 3 személyes kanapé, prémium szövettel és tömör tölgyfa lábakkal.",
    price: 245000,
    stock_quantity: 12,
    images: ["/images/products/nordic-soft-kanape-1.webp", "/images/products/nordic-soft-kanape-2.webp", "/images/products/nordic-soft-kanape-3.webp"],
    category_id: "cat-1",
    material: "Szövet, Tölgyfa",
    color: "Világosszürke",
    is_featured: true,
    is_active: true,
  },
  {
    id: "prod-2",
    name: "Urban Velvet Sarokkanapé",
    slug: "urban-velvet-sarokkanape",
    description: "Elegáns bársony borítású sarokkanapé, amely bármely nappali központi eleme lehet.",
    price: 360000,
    stock_quantity: 5,
    images: ["/images/products/urban-velvet-sarokkanape-1.webp", "/images/products/urban-velvet-sarokkanape-2.webp", "/images/products/urban-velvet-sarokkanape-3.webp"],
    category_id: "cat-1",
    material: "Bársony",
    color: "Mélykék",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-3",
    name: "Cloud modularis kanapé",
    slug: "cloud-modularis-kanape",
    description: "Végtelen variációs lehetőség a Cloud moduláris rendszerrel. Extra puha kényelem.",
    price: 480000,
    stock_quantity: 8,
    images: ["/images/products/cloud-modularis-kanape-1.webp", "/images/products/cloud-modularis-kanape-2.webp", "/images/products/cloud-modularis-kanape-3.webp"],
    category_id: "cat-1",
    material: "Pamutvászon",
    color: "Törtfehér",
    is_featured: false,
    is_active: true,
  },

  // --- Asztalok (cat-2) ---
  {
    id: "prod-4",
    name: "Solid Oak Étkezőasztal",
    slug: "solid-oak-etkezoasztal",
    description: "Tömör tölgyfából készült, rusztikus de minimalista étkezőasztal 6-8 személyre.",
    price: 185000,
    stock_quantity: 15,
    images: ["/images/products/solid-oak-etkezoasztal-1.webp", "/images/products/solid-oak-etkezoasztal-2.webp", "/images/products/solid-oak-etkezoasztal-3.webp"],
    category_id: "cat-2",
    material: "Tömör tölgy",
    color: "Natúr tölgy",
    is_featured: true,
    is_active: true,
  },
  {
    id: "prod-5",
    name: "Glass Vision Dohányzóasztal",
    slug: "glass-vision-dohanyzoasztal",
    description: "Edzett üvegfelület és fém váz kombinációja a légies megjelenésért.",
    price: 55000,
    stock_quantity: 25,
    images: ["/images/products/glass-vision-dohanyzoasztal-1.webp", "/images/products/glass-vision-dohanyzoasztal-2.webp", "/images/products/glass-vision-dohanyzoasztal-3.webp"],
    category_id: "cat-2",
    material: "Üveg, Fém",
    color: "Fekete / Átlátszó",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-6",
    name: "WorkSpace Íróasztal",
    slug: "workspace-iroasztal",
    description: "Ergonómikus kialakítású íróasztal beépített kábelkezelővel és fiókokkal.",
    price: 120000,
    stock_quantity: 10,
    images: ["/images/products/workspace-iroasztal-1.webp", "/images/products/workspace-iroasztal-2.webp", "/images/products/workspace-iroasztal-3.webp"],
    category_id: "cat-2",
    material: "MDF, Fém",
    color: "Antracit",
    is_featured: false,
    is_active: true,
  },

  // --- Székek (cat-3) ---
  {
    id: "prod-7",
    name: "Comfort Diner Szék",
    slug: "comfort-diner-szek",
    description: "Párnázott étkezőszék ergonomikus háttámlával, bükkfa lábakkal.",
    price: 45000,
    stock_quantity: 40,
    images: ["/images/products/comfort-diner-szek-1.webp", "/images/products/comfort-diner-szek-2.webp", "/images/products/comfort-diner-szek-3.webp"],
    category_id: "cat-3",
    material: "Szövet, Bükkfa",
    color: "Bézs",
    is_featured: true,
    is_active: true,
  },
  {
    id: "prod-8",
    name: "Classic Leather Fotel",
    slug: "classic-leather-fotel",
    description: "Valódi bőr fotel klasszikus designnal, amely az iroda vagy a könyvtárszoba dísze lehet.",
    price: 210000,
    stock_quantity: 4,
    images: ["/images/products/classic-leather-fotel-1.webp", "/images/products/classic-leather-fotel-2.webp", "/images/products/classic-leather-fotel-3.webp"],
    category_id: "cat-3",
    material: "Bőr, Fa",
    color: "Barna",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-9",
    name: "Minimalist Bar Szék",
    slug: "minimalist-bar-szek",
    description: "Modern bárszék, állítható magassággal és kényelmes lábtartóval.",
    price: 52000,
    stock_quantity: 18,
    images: ["/images/products/minimalist-bar-szek-1.webp", "/images/products/minimalist-bar-szek-2.webp", "/images/products/minimalist-bar-szek-3.webp"],
    category_id: "cat-3",
    material: "Fém, PU bőr",
    color: "Fekete",
    is_featured: false,
    is_active: true,
  },

  // --- Szekrények (cat-4) ---
  {
    id: "prod-10",
    name: "Grande Gardrób",
    slug: "grande-gardrob",
    description: "Hatalmas ruhásszekrény tolóajtókkal, tükörrel és belső világítással.",
    price: 320000,
    stock_quantity: 6,
    images: ["/images/products/grande-gardrob-1.webp", "/images/products/grande-gardrob-2.webp", "/images/products/grande-gardrob-3.webp"],
    category_id: "cat-4",
    material: "Laminált bútorlap",
    color: "Fehér tölgy",
    is_featured: true,
    is_active: true,
  },
  {
    id: "prod-11",
    name: "Retro Comod",
    slug: "retro-comod",
    description: "A 60-as évek stílusát idéző komód 4 fiókkal és 2 ajtóval.",
    price: 95000,
    stock_quantity: 14,
    images: ["/images/products/retro-comod-1.webp", "/images/products/retro-comod-2.webp", "/images/products/retro-comod-3.webp"],
    category_id: "cat-4",
    material: "Diófa furnér",
    color: "Dió",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-12",
    name: "Glass Vitrin",
    slug: "glass-vitrin",
    description: "Elegáns üvegajtós szekrény kedvenc tárgyai bemutatására.",
    price: 145000,
    stock_quantity: 9,
    images: ["/images/products/glass-vitrin-1.webp", "/images/products/glass-vitrin-2.webp", "/images/products/glass-vitrin-3.webp"],
    category_id: "cat-4",
    material: "Üveg, Fa",
    color: "Sötétszürke",
    is_featured: false,
    is_active: true,
  },

  // --- Ágyak (cat-5) ---
  {
    id: "prod-13",
    name: "Sweet Dreams Ágykeret",
    slug: "sweet-dreams-agykeret",
    description: "Szövettel kárpitozott franciaágy keret beépített tárolóval.",
    price: 245000,
    stock_quantity: 7,
    images: ["/images/products/sweet-dreams-agykeret-1.webp", "/images/products/sweet-dreams-agykeret-2.webp", "/images/products/sweet-dreams-agykeret-3.webp"],
    category_id: "cat-5",
    material: "Szövet, MDF",
    color: "Szürke",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-14",
    name: "King Solid Wood Ágy",
    slug: "king-solid-wood-agy",
    description: "Masszív fenyőfa ágykeret, amely generációkon át kiszolgálja a családot.",
    price: 195000,
    stock_quantity: 5,
    images: ["/images/products/king-solid-wood-agy-1.webp", "/images/products/king-solid-wood-agy-2.webp", "/images/products/king-solid-wood-agy-3.webp"],
    category_id: "cat-5",
    material: "Tömör fenyő",
    color: "Natúr",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-15",
    name: "Modern Platform Bed",
    slug: "modern-platform-bed",
    description: "Fejtámla nélküli, minimalista platform ágy, modern hálószobákba.",
    price: 155000,
    stock_quantity: 11,
    images: ["/images/products/modern-platform-bed-1.webp", "/images/products/modern-platform-bed-2.webp", "/images/products/modern-platform-bed-3.webp"],
    category_id: "cat-5",
    material: "Laminált fa",
    color: "Világos kőris",
    is_featured: false,
    is_active: true,
  },

  // --- Polcok (cat-6) ---
  {
    id: "prod-16",
    name: "Library Wall Polcrendszer",
    slug: "library-wall-polcrendszer",
    description: "Moduláris falra szerelhető polcrendszer könyvgyűjtőknek.",
    price: 85000,
    stock_quantity: 30,
    images: ["/images/products/library-wall-polcrendszer-1.webp", "/images/products/library-wall-polcrendszer-2.webp", "/images/products/library-wall-polcrendszer-3.webp"],
    category_id: "cat-6",
    material: "Fém, Fa",
    color: "Fekete / Tölgy",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-17",
    name: "Minimal Floating Shelf",
    slug: "minimal-floating-shelf",
    description: "Láthatatlan rögzítésű fali polc, több méretben és színben elérhető.",
    price: 18000,
    stock_quantity: 100,
    images: ["/images/products/minimal-floating-shelf-1.webp", "/images/products/minimal-floating-shelf-2.webp", "/images/products/minimal-floating-shelf-3.webp"],
    category_id: "cat-6",
    material: "MDF",
    color: "Fehér",
    is_featured: false,
    is_active: true,
  },
  {
    id: "prod-18",
    name: "ZigZag Bookshelf",
    slug: "zigzag-bookshelf",
    description: "Különleges, geometrikus formájú könyvespolc modern terekbe.",
    price: 64000,
    stock_quantity: 15,
    images: ["/images/products/zigzag-bookshelf-1.webp", "/images/products/zigzag-bookshelf-2.webp", "/images/products/zigzag-bookshelf-3.webp"],
    category_id: "cat-6",
    material: "Laminált bútorlap",
    color: "Fekete",
    is_featured: false,
    is_active: true,
  },
];

// ------------------------------------------------------------
// Rendelések (3 db)
// ------------------------------------------------------------
export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-1",
    status: "delivered",
    total_amount: 290000,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 napja
    items: [
      { id: "item-1", product_id: "prod-1", product_name: "Nordic Soft Kanapé", unit_price: 245000, quantity: 1 },
      { id: "item-2", product_id: "prod-7", product_name: "Comfort Diner Szék", unit_price: 45000, quantity: 1 },
    ],
    shipping_address: {
      full_name: "Kovács Anna",
      email: "anna@example.com",
      zip_code: "1051",
      city: "Budapest",
      address: "Deák Ferenc utca 5.",
      country: "Magyarország",
    },
  },
  {
    id: "ord-2",
    status: "shipped",
    total_amount: 185000,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 napja
    items: [
      { id: "item-3", product_id: "prod-4", product_name: "Solid Oak Étkezőasztal", unit_price: 185000, quantity: 1 },
    ],
    shipping_address: {
      full_name: "Kovács Anna",
      email: "anna@example.com",
      zip_code: "1051",
      city: "Budapest",
      address: "Deák Ferenc utca 5.",
      country: "Magyarország",
    },
  },
  {
    id: "ord-3",
    status: "pending",
    total_amount: 110000,
    created_at: new Date().toISOString(),
    items: [
      { id: "item-4", product_id: "prod-5", product_name: "Glass Vision Dohányzóasztal", unit_price: 55000, quantity: 2 },
    ],
    shipping_address: {
      full_name: "Kovács Anna",
      email: "anna@example.com",
      zip_code: "1051",
      city: "Budapest",
      address: "Deák Ferenc utca 5.",
      country: "Magyarország",
    },
  },
];

// ------------------------------------------------------------
// Mock User
// ------------------------------------------------------------
export const MOCK_USER: User = {
  id: "user-1",
  full_name: "Kovács Anna",
  email: "anna@example.com",
  role: "customer",
  shipping_address: {
    full_name: "Kovács Anna",
    email: "anna@example.com",
    zip_code: "1051",
    city: "Budapest",
    address: "Deák Ferenc utca 5.",
    country: "Magyarország",
  },
};
